# Generated by Django 4.2.7 on 2023-11-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='название материала')),
                ('material_description', models.TextField(blank=True, null=True, verbose_name='описание материала')),
                ('material_preview', models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='materials/', verbose_name='изображение материала')),
                ('material_url', models.URLField(blank=True, null=True, verbose_name='ссылка на видео материала')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, verbose_name='название раздела')),
                ('section_preview', models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='sections/', verbose_name='изображение раздела')),
                ('section_description', models.TextField(blank=True, null=True, verbose_name='описание раздела')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
    ]
